#!/bin/sh
cd "${0%/*}" || exit 1
. "${WM_PROJECT_DIR:?}/bin/tools/RunFunctions"

runApplication blockMesh
runApplication surfaceCheck constant/triSurface/obstruction.stl
runApplication snappyHexMesh
runApplication createPatch
runApplication checkMesh
runApplication foamRun -solver incompressibleFluid
runApplication foamPostProcess -dict system/sampleDict -latestTime
